version: '3.1'

services:

  wordpress:
    container_name: wp-1  
    image: wordpress:latest
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html  
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  db:
    container_name: mysql-1  
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password  
    restart: "no"  
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin: 
    container_name: phpmyadmin-1     
    depends_on:      
    - db    
    image: phpmyadmin/phpmyadmin    
    links:      
    - db    
    ports:      
    - "8080:80"    
    restart: "no"